poll_interval: 6
test_configuration:
  report: lighthouse
  simulate_device: nexus_5
  url: https://www.google.com
  video: false
requirements:
  structure_score: 98
  onload_duration: 98
  gtmetrix_grade: A