poll_interval: 6
test_configuration:
  report: lighthouse
  simulate_device: nexus_5
  url: https://www.google.com
  video: 0
requirements:
  structure_score: 50
  onload_duration: 98
  gtmetrix_grade: A