name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    needs: read-node-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.read-node-version.outputs.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci --no-fund
      - run: npm test
      - run: npm run build
      - run: npm run package

  read-node-version:
    name: Read .nvmrc
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

  runs-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          api_key: ${{ secrets.GTMETRIX_API_KEY }}
          configuration_file: ./config.yml
